refactor: change way to store fast outs and high outs
fkula5/steel-dart-rzeszow-backend pull request #11
Opened 2023-09-19 18:27 UTC by fkula5

2023-09-19 19:05 UTC, marioooo0o requested changes
Daj znać co myślisz

2023-09-19 19:05 UTC, marioooo0o commented on app/Http/Requests/GameStoreRequest.php
> +            'player_one_high_outs' => ['array'],
Jakie dane tu będą? Inty? Jakieś typy ze słownika? Warto dodać też jaki typ pola required|sometimes|nullable

Widzę że id więc pasuje sprawdzać czy są exists w tebeli

2023-09-19 19:05 UTC, marioooo0o commented on app/Services/GameService.php
> +    private function createHighOuts(array $highOuts, int $gameId, int $playerId): void
Nie mam jak podjerzec kontrolera ale wydaje mi się że game Id jest dalej model binding

2023-09-21 09:40 UTC, fkula5 commented on app/Http/Requests/GameStoreRequest.php
> +            'player_one_high_outs' => ['array'],
tu będą inty, ale może ich też nie byc

2023-09-21 11:19 UTC, marioooo0o commented on app/Http/Requests/GameStoreRequest.php
> +            'player_one_high_outs' => ['array'],
> tu będą inty, ale może ich też nie byc
> 

Dasz jakiś przykład? Co może być 20 lub "20" czy rzeczywiście jakiś tekst, ważne to żebyś wykluczył jakieś podatności jak przesłanie złośliwego pliku

2023-09-22 19:33 UTC, marioooo0o requested changes

2023-09-22 19:33 UTC, marioooo0o commented on app/Http/Requests/GameStoreRequest.php
> +            'player_one_high_outs' => ['sometimes','array'],
Dalej nie ma typu

2023-09-22 19:33 UTC, marioooo0o commented on app/Services/GameService.php
> +    private function updatePlayerStats(Player $player, $score, $opponentScore, $avg, $max): void
brak typów w parametrach

2023-09-28 08:29 UTC, marioooo0o approved these changes
Wydaje się być w porządku

2023-09-28 08:29 UTC, merged